# Generated by Django 5.0 on 2024-02-24 15:42

import django.db.models.deletion
import mngmntsystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userName', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password', models.TextField(max_length=128)),
                ('fullName', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('fullName', models.TextField(max_length=128)),
                ('phoneNum', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('phoneNum', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
                ('fullName', models.TextField(max_length=128)),
                ('password', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('vehicleType', models.TextField(max_length=128)),
                ('brand', models.TextField(max_length=128)),
                ('capacity', models.IntegerField()),
                ('plateNum', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenanceID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('maintenanceDate', models.DateField()),
                ('availableDate', models.DateField()),
                ('maintenanceReason', models.TextField()),
                ('vehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mngmntsystem.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('bookingDate', models.DateField()),
                ('bookingTime', models.TimeField(default=mngmntsystem.models.current_time)),
                ('purpose', models.TextField(max_length=256)),
                ('bookingStatus', models.TextField(default='Pending', max_length=8)),
                ('driverID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mngmntsystem.driver')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mngmntsystem.user')),
                ('vehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mngmntsystem.vehicle')),
            ],
        ),
    ]
